library("shiny")

shinyUI(fluidPage(
    # Application title
    titlePanel("GeneVis - Visualisation of gene expression data"),
    hr(),
    sidebarLayout(
        sidebarPanel(width=3,
                     p('Upload a gene expression file.'),
                     fileInput('file1', label="", accept = c('text/csv',
                                                             'text/comma-separated-values',
                                                             'text/tab-separated-values', 
                                                             '.csv', '.tsv', '.txt')
                     ),
                     code('(A default table is supplied.)')
        ),
        mainPanel(width=9,
            h2("This shiny app attempts to aid biologists visualise gene expression data."),
            p("The user supplies a text file of gene expression values generated 
                from an experiment comparing gene levels in biological samples."),
            p("There is an assumption of understanding of what these files contain. 
              However, a default file has ben supplied so people can see the app in action."),
            p("The idea is for a biologist to upload his/her file - commonly generated by 
              high throughput sequencing facilities where biologists are left with no help 
                in trying to understand the output - and inspect the data with little or no 
              informatics or statistical experience required."),
            p("Functionality is split into a number of panels. Each panel allows the user 
              to control the functionality with control sliders, or text input."),
            p("The goal is to generate data and plots to help scientists better 
              understand the gene expression differences in large sample sets."),
            strong(em("Please allow a little time for data loading and processing within the 
                      differential expression panel - thanks :)"))
        )
    ),
    tabsetPanel(
        tabPanel('Data',
                 hr(),
                 fluidRow(column(6, htmlOutput("TestSet")),
                          column(6, htmlOutput("ControlSet"))
                 ),
                 div(dataTableOutput('content'), 
                     style="font-family: Arial,Arial; font-size:90%")
        ),
        tabPanel('Visualisation Plot',
                 hr(),
                 fluidRow(column(12, htmlOutput("TopGenes"))
                 ),
                 fluidRow(column(12, plotOutput("Heatmap", height="800px")))
        ),
        tabPanel('Differential Expression',
                 hr(),
                 fluidRow(column(6, htmlOutput("P_Value")),
                          column(6, htmlOutput("FoldChange"))
                 ),
                 fluidRow(column(10, plotOutput("MA_plot", height="600px")))
        )
        
    )
    
))